language: node_js
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  # Set the directory to push to pages
  # local-dir: src
  on:
    branch: master
